#!/usr/bin/env bash
set -euo pipefail
task_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
task_compiler="${CXX:-g++}"
task_output="${1:-$task_dir/tape.so}"
task_metadata="$(dirname -- "$task_output")/build-info.lua"
task_temporary="$(mktemp "${task_output}.build.XXXXXX")"
task_meta_temporary="$(mktemp "${task_metadata}.build.XXXXXX")"
trap 'rm -f -- "$task_temporary" "$task_meta_temporary"' EXIT
# Keep Hyprland symbols unresolved: the running compositor supplies them.
# Lua headers must match Hyprland's Lua build (currently the default lua pkg).
read -r -a task_flags <<< "$(pkg-config --cflags hyprland lua)"
task_version="$(pkg-config --modversion hyprland)"
task_git_hash="$("$task_compiler" "${task_flags[@]}" -dM -E -x c++ \
  -include hyprland/src/version.h /dev/null |
  awk '$2 == "GIT_COMMIT_HASH" { gsub(/"/, "", $3); print $3 }')"
# These values are generated Lua literals, so admit only expected tokens.
[[ "$task_version" =~ ^[[:alnum:]_.+-]+$ ]] || {
  printf 'Unexpected Hyprland version: %s\n' "$task_version" >&2
  exit 1
}
[[ "$task_git_hash" =~ ^[[:xdigit:]]{40}$ ]] || {
  printf 'Could not read a valid Hyprland Git hash from the build headers\n' >&2
  exit 1
}
"$task_compiler" -std=c++26 -shared -fPIC -fno-gnu-unique -O2 -Wall -Wextra \
  "${task_flags[@]}" "$task_dir/tape.cpp" -o "$task_temporary"
printf '%s\nreturn { version = "%s", git_hash = "%s" }\n' \
  '-- Generated by build.sh from the headers used to compile tape.so.' \
  "$task_version" "$task_git_hash" > "$task_meta_temporary"
# Never truncate a .so that a compositor may already have mapped.
chmod 755 "$task_temporary"
mv -f -- "$task_temporary" "$task_output"
chmod 644 "$task_meta_temporary"
mv -f -- "$task_meta_temporary" "$task_metadata"
printf 'Built %s\n' "$task_output"
printf 'Build metadata: %s\n' "$task_metadata"
"$task_compiler" --version | head -n 1
printf 'Hyprland %s (%s), Lua %s\n' "$task_version" "$task_git_hash" "$(pkg-config --modversion lua)"
